# Generated by Django 4.2.7 on 2023-11-06 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0003_community_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 16, 30, 34, 409489, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('Board_id', models.AutoField(primary_key=True, serialize=False)),
                ('idea_a', models.TextField(max_length=300)),
                ('idea_b', models.TextField(max_length=300)),
                ('idea_c', models.TextField(max_length=300)),
                ('pick', models.TextField(max_length=300)),
                ('comment', models.TextField(max_length=300)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politician.community')),
            ],
        ),
    ]
