# Generated by Django 4.2.7 on 2023-11-06 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0004_alter_community_deadline_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 16, 45, 12, 491942, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
