# Generated by Django 4.2.7 on 2023-11-06 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0015_remove_community_comment_alter_community_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pick',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 18, 11, 8, 844893, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
