# Generated by Django 4.2.7 on 2023-11-06 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_community_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 16, 50, 11, 473571, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
