# Generated by Django 4.2.7 on 2023-11-06 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_board_id_board_board_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 17, 25, 26, 942260, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
