# Generated by Django 4.2.7 on 2023-11-06 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_board_comment_alter_community_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 17, 37, 59, 474818, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
