# Generated by Django 4.2.7 on 2023-11-06 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_community_comment_alter_community_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='comment',
        ),
        migrations.AlterField(
            model_name='community',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 18, 5, 20, 749353, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('idea_a', models.TextField(max_length=300)),
                ('idea_b', models.TextField(max_length=300)),
                ('idea_c', models.TextField(max_length=300)),
                ('pick', models.TextField(max_length=300)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.community')),
            ],
        ),
    ]
